### ISSUE TITLE
ADR: stable API's for OpenSCD-core/SCL-libary

### ISSUE THREAD

**Issue by Sander3003** [openscd/open-scd-core#101] opened 2023-05-17 12:35 UTC
As a plug-in developer
I would like to know the architecture and principles of OpenSCD-core / OpenSCD-next
So I understand the general principles of the software 

Acceptance criteria:
Be backwards compatible
ADR

**Comment by Sander3003** [comment] 2023-05-31 12:58
@JakobVogelsang can you write something about the OpenSCD-core architecture and the motivaitons behind it?

**Comment by juancho0202** [comment] 2024-02-01 09:15
Duplicate of https://github.com/openscd/open-scd/issues/1428

**Closed by juancho0202** 2024-02-01 09:15 UTC
